const KesmasModel = {
  _id: null,
  _rid: null,
  respondenSakit: "",
  penyakitResponden: "", // line array
  anggotaSakit: "",
  penyakitAnggota: "", // line array
  stunting: "",
  sebabStunting: "", // line array
  wabah: "",
  infoWabah: "",
  tempatBerobat: [],
  alasanKeDukun: "", // line array
  aksesBerobat: "",
  infoAksesBerobat: "",
  asuransiKesehatan: "",
  infoAsuransiKesehatan : "",
  kelayakanFaskes: "",
  infoKelayakanFaskes: "",
  layananPTFI: "",
  pernahLayananPTFI: "",
  infoLayananPTFI: "",
  sumberAirMinum: [],
  merebusAir: "",
  konsumsiAir: "",
  sumberAirBersih: [],
  masalahAir: [],
  solusiMasalahAir: "",
  saranaBAB: "",
  infoSaranaBAB: "",
  saranaAirLimbah: "",
  kelolaSampah: "",
  genanganAir: "",
  nyamukDiGenangan: "",
  indikasiVektor: "",
  kebersihanRumah: "",
  komunitasSampah: "", // line array
  plafon: "",
  dinding: "",
  lantai: "",
  jendelaKamar: "",
  jendelaRuang: "",
  ventilasi: "",
  pencahayaan: "",
  caraCegahMalaria: [],
  konsumsiSayur: "",
  olahraga: "",
  menjagaKebersihanDiri: [],
  perokok: "",
  tempatMerokok: "",
  konsumsiMiras: "",
  frekuensiMiras: "",
  dampakMiras: [],
}

export default KesmasModel;