export const ModelPersepsi = {
  _id: null,
  _rid: null,
  tahuRencana: "",
  sumberInformasi: "",
  // dampakPTFI: [],
  dampakUmum: [],
  peluangDanMinat: "",
  infoPeluangDanMinat: "",
  pilihanKerja: "",
  infoPilihanKerja: "",
  dampakLingkungan: "",
  infoDampakLingkungan: "",
  dampakKesehatan: "",
  infoDampakKesehatan: "",
  dampakLayananPublik: "",
  infoLampakLayananPublik: "",
  dampakAdat: "",
  infoDampakAdat: "",
  gotongRoyong: "",
  infoGotongRoyong: "",
  sikap: "",
  infoSikap: "",
  dampakKesulitan: "",
  infoDampakKesulitan: "",
}

// Nawaripi,
// Koperapoka,
// Nayaro
// Tipuka dan
// Ayuka
export const ModelNelayan = {
  _id: null,
  _rid: null,
  fungsiBadanAir: [],
  polaKegiatan: [],
  alatTangkapIkan: [],
  frekuensiTangkapIkan: "",
  hasilTangkapIkan: "",
  dampakTailing: "",
  infoDampakTailing: "",
  perbedaanHasil: "",
  infoPerbedaanHasil: "",
  bantuanPTFI: [],
  menjualHasilTangkapan: [],
  pembeliHasilTangkapan: [],
  harapanUntukPTFI: [],
  harapanUntukYPMAK: [],
  harapanUntukPemda: [],
}
