const PersepsiModel = {
  _id: null,
  _rid: null,
  tahuRencana: "",
  sumberInformasi: "",
  // dampakPTFI: [],
  dampakUmum: [],
  peluangDanMinat: "",
  infoPeluangDanMinat: "",
  pilihanKerja: "",
  infoPilihanKerja: "",
  dampakLingkungan: "",
  infoDampakLingkungan: "",
  dampakKesehatan: "",
  infoDampakKesehatan: "",
  dampakLayananPublik: "",
  infoLampakLayananPublik: "",
  dampakAdat: "",
  infoDampakAdat: "",
  gotongRoyong: "",
  infoGotongRoyong: "",
  sikap: "",
  infoSikap: "",
  dampakKesulitan: "",
  infoDampakKesulitan: "",
}

export default PersepsiModel;